language: python

python: '3.6'
sudo: false

# We don't care about Travis' python versions, we install conda anyway
env:
  global:
    - AWS_DEFAULT_REGION=ap-northeast-1
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

before_install:
  - python3 -m venv venv
  - source venv/bin/activate

install:
  - pip3 install -r requirements.txt
  - pip3 install awscli
  - pip3 install boto3

script:
  # run tests
  - echo "[INFO] skip test"

before_deploy:
  - echo "before deploy"
  # - mkdir -p dist
  # create zip for each lambda folder in src
  # - for i in src/*/; do .travis/build_lambda.sh "$i"; done

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: true
